### ISSUE TITLE
Simplify config files by creating Service struct for OpenRC services

### ISSUE THREAD

**Issue by yonkornilov** [yonkornilov/snowcapper#10]
At the moment, to create OpenRC services your config must specify the OpenRC scripts in the `files` list of a Package struct:
```
    binaries:
      - name: vault
        mode: 0755
        src: https://releases.hashicorp.com/vault/0.10.0/vault_0.10.0_linux_amd64.zip
        format: zip
    files:
      - path: /etc/vault/config.hcl
        mode: 0700
        content: |
          ...
      - path: /etc/init.d/vault
        mode: 0700
        content: |
          NAME=vault
          DAEMON=/usr/bin/$NAME

          depend() {
          ...
          }

          start() {
          ....
          }

          stop () {
          ...
          }
    inits:
      - type: openrc
        content: vault
```
This could be simplified by adding a service struct that would go in a Package struct's `services` list:
```
    binaries:
      - name: vault
        mode: 0755
        src: https://releases.hashicorp.com/vault/0.10.0/vault_0.10.0_linux_amd64.zip
        format: zip
    files:
      - path: /etc/vault/config.hcl
        mode: 0700
        content: |
          ...
    services:
      - binary: vault
        args:
          - "server"
          - "-config /etc/vault/config.hcl"
    inits:
      - type: openrc
        content: vault
```
