### ISSUE TITLE
Allow for local binary source

### ISSUE THREAD

**Issue by yonkornilov** [yonkornilov/snowcapper#18]
Atm a binary source must be remote:
```
binaries:
  - name: vault
    mode: 0755
    src: https://releases.hashicorp.com/vault/0.10.0/vault_0.10.0_linux_amd64.zip
    format: zip
```
There should be support for a local source:
```
binaries:
  - name: vault
    mode: 0755
    src: /tmp/vault_0.10.0_linux_amd64.zip
    format: zip
```
