### ISSUE TITLE
Extensible profiles

### ISSUE THREAD

**Issue by deedubs** [yonkornilov/snowcapper#32]
It would be interesting to be able to layer snowcapper configurations on one another. 

It could be a way to create community-curated bases to build on.
 
```
extends:
  - src: https://example.com/cis_hardened.snc 
    src_hash: a6b4b6db132f3bbe6fbb77f76228ffa45bd55a5a1ab83ff043c2c665c3f5a744

packages:
  - name: vault
    binaries:
      - name: vault
        mode: 0755
        src: https://releases.hashicorp.com/vault/0.10.0/vault_0.10.0_linux_amd64.zip
        src_hash: a6b4b6db132f3bbe6fbb77f76228ffa45bd55a5a1ab83ff043c2c665c3f5a744
        format: zip
```

In that example, you would start with a machine that followed the CIS Benchmarks and then installs your own configuration on top.
